#!/bin/bash

for file in nev_codes/nev_*$1*py;
do
  class=${file:14:-3}
  file=E_NEV_${class}_E3.inl
  echo $class
  python nev_codes/nev_$class.py --commentE3 > new_inl/$file;
  sed -i 's/,USAGE_\(.*\)},/,USAGE_\1, STORAGE_Memory},/g' new_inl/$file
  diff -q current_inl/$file new_inl/$file
done
