#!/bin/bash

for file in nev_codes_DF/nev_*$1*py;
do
  class=${file:17:-3}
  file=E_NEV_${class}_DF.inl
  echo $class
  python nev_codes_DF/nev_$class.py > new_inl/$file;
  sed -i 's/,USAGE_\(.*\)},/,USAGE_\1, STORAGE_Memory},/g' new_inl/$file
  diff -q current_inl/$file new_inl/$file
done
