#!/bin/bash

for file in lcc_codes_DF/lcc_*$1*py;
do
  class=${file:17:-3}
  file=E_LCC_${class}_DFE4.inl
  echo $class
  python lcc_codes_DF/lcc_$class.py --cumulantE4 > new_inl/$file;
  sed -i 's/,USAGE_\(.*\)},/,USAGE_\1, STORAGE_Memory},/g' new_inl/$file
  diff -q current_inl/$file new_inl/$file
done
